# On first boot, the device will automatically invoke zero touch provisioning

# Login as admin and disable ZTP permanently so it doesn't prompt again on reboot:

admin

config t

zerotouch cancel

# The box will reboot. Once up, login as admin with no password. Enter config mode:

config t
hostname csw1.iad1
username admin privilege 15 secret 0 <password>
enable secret 0 <password>
management ssh
idle-timeout 30
aaa authentication login default local
aaa authorization exec default local
spanning-tree mode rapid-pvst
end
write memory
