# The following will disply on first boot:
         --- System Configuration Dialog ---

Would you like to enter the initial configuration dialog? [yes/no]: no

Would you like to terminate autoinstall? [yes]: yes

# After messages stop scrolling hit Enter

enable

config t

no banner exec
no banner login
no banner incoming
!
no call-home
!
no ip http server
no ip http authentication local
no ip http secure-server
!
hostname cr1-iad4
ip domain name newco.com
username admin privilege 15 secret 0 <password>
enable secret 0 <password>
!
service password-encryption
no ip domain lookup
!
crypto key generate rsa modulus 2048
ip ssh version 2
!
end
wr mem
