# Create admin1 user at initial dialog and enter password twice
# Login as admin1 user

configure exclusive

no call-home

hostname cr1-iad2
username admin
 group root-lr
 group cisco-support
 secret 0 <password>
!
ssh server v2
ssh server vrf default
!

# You can optionally delete the admin1 user you originally created
# no username admin1

commit label day-zero-baseline
