# Login as root

cli

configure exclusive

delete chassis auto-image-upgrade

# Configure Root Password
set system root-authentication plain-text-password 
# Enter password twice
New password:
Retype new password:

# commit to stop auto-image-upgrade

commit

delete system processes dhcp-service
delete interfaces fxp0 unit 0
delete protocols router-advertisement

set system host-name cr1-iad1

set system login user admin class super-user authentication plain-text-password
# Enter password twice
New password:
Retype new password:

set system services ssh root-login deny
set system services netconf ssh port 830

commit and quit
